### ISSUE TITLE
Change ui so that controls are not part of scene (see whiteboard

### ISSUE THREAD

**Issue by cathyatseneca** [Seneca-CDOT/RealCameras#13]

**Comment by andriibugaiov** [comment]
I will create placeholders and decouple cobtrols panel from the scene demonstrator. Then I pass the issue to Barbara as she wanted to work on the new ui.

**Comment by barbaradegraaf** [comment]
Okay that sounds good!

**Comment by andriibugaiov** [comment]
Hey, Barbara!

I have decoupled functionality and created placeholders/containers for both controls panel and scene demonstrator. Please, take a look at Application.js and new class called ControlsPanel.js. Let me know if you have any questions!

**Comment by andriibugaiov** [comment]
The master branch is updated.

**Comment by barbaradegraaf** [comment]
I have created the basic UI. I am going to rework some of it and change the style to make it more aesthetically pleasing, but it currently works enough to show tomorrow

**Comment by andriibugaiov** [comment]
Hm...for some reason I don't see your changes, Barbara...have you pushed them into master?

**Comment by barbaradegraaf** [comment]
Sorry about that. They should be in master now.
