### ISSUE TITLE
Add functionality for dynamic changing of the film's aspect ratio. Display black bars when appropriate.

### ISSUE THREAD

**Issue by cathyatseneca** [Seneca-CDOT/RealCameras#16]
add the black bars to get the correct aspect ratio

**Comment by andriibugaiov** [comment]
When working on the 'sharp threshold' bug I discovered another problem that in turn touched the aspect ration functionality. I think I got it working...Please, see my commit 'depth map target reset, aspect ratio' (file: RealCamerasDemonstrator.js, method: RealCamerasDemonstrator.prototype.onSettingsChanged = function () {...})

**Comment by barbaradegraaf** [comment]
Look good! I am pretty sure you got the aspect ratio working perfectly. I will check it over right now.
