### ISSUE TITLE
Create Survey

### ISSUE THREAD

**Issue by cathyatseneca** [Seneca-CDOT/RealCameras#18]

**Comment by cathyatseneca** [comment]
https://docs.google.com/forms/d/12FuTnvtBRmchVZssIwHbEsWUHRGK1-y0_oOeE0fjdzI/viewform

**Comment by cathyatseneca** [comment]
If you do not have form done yet, can use above.  If you have it done, don't worry about it.

**Comment by barbaradegraaf** [comment]
Okay I will use your form for the survey.
